### ISSUE TITLE
Some questions in the dataset are wrong with {tail2}

### ISSUE THREAD

**Issue by BlackHandLYH** [apoorvumang/CronKGQA#13]
Hi! @apoorvumang Amazing work here!

I found that some questions in the dataset with the type of "time_join" are wrong, in which there's a {tail2} in the template that is not correctly mapped. Some examples are:
"When Q300269 was the Q37303731 , who was the {tail2}"
"Who was {tail2} when Q6105302 was the Q41582582"

I wonder if there are some problems with templates like the following or something else?
"Who was the {tail2} when {head} was the {tail}"

Thanks!
Best,
Yonghao

**Comment by apoorvumang** [comment]
Hi Yonghao

Thanks for your interest!

Yes this question template unfortunately did not get filled properly during dataset construction, and there exist some faulty questions like you mentioned. We will fix these in a v2 of the dataset, but in order to keep consistency in the reported numbers we are not changing anything in the current version.

**Comment by BlackHandLYH** [comment]
Thanks a lot! Looking forward to v2 :)

**Comment by apoorvumang** [comment]
Closing issue here, but will leave it pinned since its important

**Comment by apoorvumang** [comment]
We have fixed the {tail2} issue. There's no other change in the dataset for now

**Comment by SRL94** [comment]
In v2 training data, some question templates still contain tail2. How could I solve it? For example,
 'uniq_id': 119922
{'question': 'Who were the Q13218630 when Q5496643 became the Q41582597', 'answers': {'Q882241', 'Q1541885', 'Q2422158', 'Q1376636', 'Q6523685', 'Q1065836', 'Q1808333', 'Q9582', 'Q4772473', 'Q1699660', 'Q279153', 'Q288402', 'Q1103618', 'Q1387262', 'Q5112043', 'Q1651726', 'Q323417', 'Q4320546', 'Q1040943', 'Q7173908', 'Q1382002', 'Q2052637', 'Q7790591', 'Q1122021', 'Q1728011', 'Q7964713', 'Q1701740', 'Q2162136', 'Q2424476', 'Q1507631', 'Q734810', 'Q1298685', 'Q1101684', 'Q1452443', 'Q1022514', 'Q388215', 'Q441832', 'Q6530684', 'Q518055', 'Q2085665', 'Q163179', 'Q887153', 'Q1691325', 'Q2577938', 'Q7329706', 'Q550255', 'Q1680034', 'Q9696', 'Q1443206', 'Q777975', 'Q8019041', 'Q1453040', 'Q5485528', 'Q2581565', 'Q3538195', 'Q524875', 'Q577160', 'Q2170925', 'Q1096821', 'Q597630', 'Q2146738', 'Q1585515', 'Q1700644', 'Q2552662', 'Q1564503', 'Q880342', 'Q1678408', 'Q1094741', 'Q5217616', 'Q1423018', 'Q240274', 'Q1634482', 'Q761572', 'Q1752310', 'Q1699478', 'Q1263994', 'Q6133672', 'Q1567156', 'Q1095314', 'Q1702036', 'Q883172', 'Q1050018', 'Q612202', 'Q1889152', 'Q2776506', 'Q1052296', 'Q1240824', 'Q13219745', 'Q1967257', 'Q2440125', 'Q1156152', 'Q597998', 'Q1507488', 'Q383144', 'Q2042456', 'Q1365631', 'Q1634414', 'Q4772230', 'Q183164', 'Q435110', 'Q467328', 'Q1268044', 'Q275876', 'Q380550', 'Q365407', 'Q1507178', 'Q6251694', 'Q1095418', 'Q9640', 'Q1700317', 'Q1360283', 'Q1680094', 'Q1507456', 'Q5126491', 'Q1067999', 'Q1680954', 'Q2502543', 'Q1747642', 'Q1108617', 'Q366388', 'Q579660', 'Q1378052', 'Q7298821', 'Q1606695', 'Q2078864', 'Q719965', 'Q775070', 'Q723488', 'Q1517696', 'Q1755662', 'Q13219098', 'Q1294506', 'Q9588', 'Q1701048', 'Q599174', 'Q4516562', 'Q1610249', 'Q1680336', 'Q5074810', 'Q1626038', 'Q888112', 'Q2638829', 'Q1292691', 'Q1356413', 'Q5541977', 'Q5126603', 'Q6144544', 'Q2522627', 'Q658433', 'Q1573501', 'Q278928', 'Q183430', 'Q1356392', 'Q1253601', 'Q1627908', 'Q4516506', 'Q1373076', 'Q464733', 'Q1651144', 'Q7350248', 'Q1608149', 'Q1699069', 'Q5343032'}, 'answer_type': 'entity', 'template': 'Who were the {tail2} when {head} became the {tail}', 'entities': {'Q5496643', 'Q41582597', 'Q13218630'}, 'times': set(), 'relations': {'P39'}, 'type': 'time_join', 'annotation': {'head': 'Q5496643', 'tail': 'Q41582597'}, 'uniq_id': 119922, 'paraphrases': ['Who were the member of the US House of Representatives when Freda Corbet became the Member of the 38th Parliament of the United Kingdom', 'Who were the Member of the House of Representatives when Freda Corbet became the Member of the 38th Parliament of the United Kingdom', 'Who were the US representative when Freda Corbet became the Member of the 38th Parliament of the United Kingdom', 'Who were the Member of the House of Representatives when Freda Corbet became the Member of the 38th Parliament of the United Kingdom', 'Who were the member of the US House of Representatives when Freda Corbet became the Member of the 38th Parliament of the United Kingdom', 'Who were the U.S. congresswoman when Freda Corbet became the Member of the 38th Parliament of the United Kingdom', 'Who were the U.S. representative when Freda Corbet became the Member of the 38th Parliament of the United Kingdom', 'Who were the US representative when Freda Corbet became the Member of the 38th Parliament of the United Kingdom', 'Who were the U.S. congresswoman when Freda Corbet became the Member of the 38th Parliament of the United Kingdom', 'Who were the member of the American House of Representatives when Freda Corbet became the Member of the 38th Parliament of the United Kingdom', 'Who were the U.S. congresswoman when Freda Corbet became the Member of the 38th Parliament of the United Kingdom']}

**Comment by yywhsgnd** [comment]
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jupyter/miniforge3/envs/env8/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jupyter/miniforge3/envs/env8/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jupyter/miniforge3/envs/env8/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jupyter/workspace/CronKGQA-main/qa_datasets.py", line 372, in __getitem__
    head = data['head'][index]
KeyError: 'head'

**Comment by liwenju0** [comment]
> 

have same error，did you fix it?

**Comment by SRL94** [comment]
Yes, in each question dictionary, there are two keys: "template" and
"question" (I cannot remember clearly). One shows a question like "Who is
the {head} of {tail}", one shows a question like "Who is the Q124 of Q456".
You can identify {tail2} by matching these two. The sequence of each word
is the same in them.
